<?php

use PHPUnit\Framework\TestCase;

class SomeClassTest extends TestCase
{
    private function testShouldDoStuff()
    {
    }
    protected function testShouldDoStuffProtected()
    {
    }
}

?>
-----
<?php

use PHPUnit\Framework\TestCase;

class SomeClassTest extends TestCase
{
    private function testShouldDoStuff()
    {
    }
    protected function testShouldDoStuffProtected()
    {
    }
}

?>
