# github action that rebuilds https://github.com/rectorphp/rector
# with the freshly merged rector-phpunit main
name: Dispatch Build Scoped Rector

on:
    pull_request:
        types:
            - closed

jobs:
    dispatch_build_scoped_rector:
        # only for merged pull requests in this repository, not forks
        if: github.event.pull_request.merged == true && github.repository == 'rectorphp/rector-phpunit'

        runs-on: ubuntu-latest

        steps:
            -
                name: "Trigger build_scoped_rector.yaml in rectorphp/rector-src"
                env:
                    GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                run: gh workflow run build_scoped_rector.yaml --repo rectorphp/rector-src --ref main
